# Generated by Django 2.2.5 on 2019-10-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='controller',
            field=models.ManyToManyField(to='controllers.Controller'),
        ),
    ]
