# Generated by Django 2.2.5 on 2019-10-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='controller',
        ),
    ]
