version: '3.5'

services:
  api:
    container_name: central-service
    build: .
    command: ["sh", "scripts/start.sh"]
    env_file: dev-env
    ports:
      - 4001:4001
    volumes:
      - .:/central-service
    depends_on:
      - db
    external_links:
      - weather-api:weatherapi
    environment:
      WEATHER_URL: "http://weatherapi:4000"
    networks:
      - simulator-network
      - weather-service-network

  db:
    container_name: central-db
    hostname: central-db
    image: postgres:9.6
    env_file: dev-env
    networks:
      - simulator-network
    ports:
      - 5432:5432
    volumes:
      - central-pg-data:/var/lib/postgresql/data

volumes:
  central-pg-data: {}

networks:
  simulator-network:
    external: true

  weather-service-network:
    external: true