# Generated by Django 2.2.6 on 2019-10-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='battery_level',
        ),
    ]
