# Generated by Django 2.2.7 on 2019-11-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_battery_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
