# Generated by Django 2.2.7 on 2019-11-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_active',
        ),
    ]
