# Generated by Django 2.2.7 on 2019-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_remove_module_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='rf_address',
            field=models.IntegerField(unique=True),
        ),
    ]
