# Generated by Django 2.2.5 on 2019-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('is_valid', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
