# Generated by Django 2.2.5 on 2019-10-02 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='owner',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
