# Generated by Django 2.2.7 on 2019-11-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_auto_20191120_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='timer',
            field=models.IntegerField(blank=True, default=150),
        ),
    ]
