# Generated by Django 2.2.6 on 2019-10-02 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_controller_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
