# Generated by Django 2.2.6 on 2019-10-09 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0003_auto_20191002_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ip_address', message='Incorrect IP address format', regex='^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$')]),
        ),
    ]
