# Generated by Django 2.2.6 on 2019-10-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0005_controller_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='is_valid',
            new_name='is_active',
        ),
    ]
