# Generated by Django 2.2.6 on 2019-10-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0006_auto_20191025_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='port',
        ),
    ]
