# Generated by Django 2.2.7 on 2019-11-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0008_controllerspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='permit_irrigation',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
