# Generated by Django 2.2.7 on 2019-11-20 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('controllers', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temperature', models.FloatField(default=0.0)),
                ('precipitation', models.FloatField(default=0.0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='ModulesMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('ground_humidity', models.IntegerField(default=0)),
                ('battery_level', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorsMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_consumption', models.FloatField(default=0.0)),
                ('reservoir_level', models.FloatField(default=0.0)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.Controller')),
            ],
        ),
    ]
