# Generated by Django 2.2.7 on 2019-11-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorsMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_consumption', models.FloatField(default=0.0)),
                ('reservoir_level', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ModulesMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('ground_humidity', models.IntegerField(default=0)),
                ('battery_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temperature', models.FloatField(default=0.0)),
                ('precipitation', models.FloatField(default=0.0)),
            ],
        ),
    ]
