# Generated by Django 2.2.7 on 2019-11-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        ('modules', '0001_initial'),
        ('zones', '0001_initial'),
        ('controllers', '0003_auto_20191126_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonemeasurement',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
        migrations.AddField(
            model_name='modulesmeasurement',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='modulesmeasurement',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
        migrations.AddField(
            model_name='actuatorsmeasurement',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllers.Controller'),
        ),
        migrations.AddField(
            model_name='actuatorsmeasurement',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
    ]
