# Generated by Django 2.2.6 on 2019-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuatorsmeasurement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
