# Generated by Django 2.2.6 on 2019-10-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_battery_level'),
        ('measurements', '0002_actuatorsmeasurement_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('ground_humidity', models.IntegerField(default=0)),
                ('battery_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
            ],
        ),
    ]
