# Generated by Django 2.2.6 on 2019-10-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_modulesmeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesmeasurement',
            name='is_active',
        ),
    ]
