# Generated by Django 2.2.6 on 2019-10-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_remove_modulesmeasurement_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuatorsmeasurement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='actuatorsmeasurement',
            name='water_flow',
            field=models.IntegerField(default=0),
        ),
    ]
