# Generated by Django 2.2.6 on 2019-10-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_auto_20191025_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuatorsmeasurement',
            name='water_flow',
        ),
    ]
