# Generated by Django 2.2.7 on 2019-11-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_auto_20191106_1450'),
        ('measurements', '0006_remove_actuatorsmeasurement_water_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_temperature', models.FloatField(default=0.0)),
                ('air_temperature', models.FloatField(default=0.0)),
                ('precipitation', models.FloatField(default=0.0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone')),
            ],
        ),
    ]
