# Generated by Django 2.2.6 on 2019-10-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='ambient_temperature',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='precipitation',
        ),
    ]
