# Generated by Django 2.2.6 on 2019-11-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_auto_20191024_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
