# Generated by Django 2.2.7 on 2019-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_zone_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
