# Generated by Django 2.2.7 on 2019-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_auto_20191106_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zip',
            field=models.CharField(max_length=9),
        ),
    ]
