# Generated by Django 2.2.7 on 2019-11-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
    ]
